import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SideNavigation from "./_components/SideNavigation";
import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ai-content",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className=" md:w-64 fixed hidden md:block ">
        <SideNavigation />
      </div>
      <div className="md:ml-64">
        <Header/>
        {children}
      </div>
    </div>
  );
}
